# Generated by Django 4.2.27 on 2026-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={'ordering': ['period_date']},
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='actual_closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('RC', '✅ Reconciled'), ('DC', '⚠️ Discrepancy')], default='NS', max_length=2),
        ),
    ]
