# Generated by Django 4.2.27 on 2026-04-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0007_journalentryline_invoice_number_and_more'),
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depreciation_method', models.CharField(choices=[('SL', 'Straight Line'), ('RB', 'Reducing Balance')], default='SL', max_length=2)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, help_text='Annual rate in percentage', max_digits=5)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('is_disposed', models.BooleanField(default=False)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_accumulated', to='finance.account')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='finance.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_expense', to='finance.account')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
    ]
