# Generated by Django 4.2.29 on 2026-03-13 11:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], max_length=20, verbose_name='period type')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('is_closed', models.BooleanField(default=False, verbose_name='is closed')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
            options={
                'verbose_name': 'Tax Period',
                'verbose_name_plural': 'Tax Periods',
                'ordering': ['-start_date'],
                'unique_together': {('company', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_type', models.CharField(choices=[('BALANCE_SHEET', 'Balance Sheet'), ('PROFIT_LOSS', 'Profit & Loss'), ('CASH_FLOW', 'Cash Flow Statement'), ('NOTES', 'Notes to Accounts')], max_length=20, verbose_name='statement type')),
                ('statement_data', models.JSONField(default=dict, verbose_name='statement data')),
                ('is_approved', models.BooleanField(default=False, verbose_name='is approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('tax_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.taxperiod')),
            ],
            options={
                'verbose_name': 'Financial Statement',
                'verbose_name_plural': 'Financial Statements',
                'ordering': ['-tax_period__end_date', 'statement_type'],
            },
        ),
        migrations.CreateModel(
            name='BeneficialOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company'), ('TRUST', 'Trust'), ('OTHER', 'Other')], max_length=20, verbose_name='owner type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.TextField(verbose_name='address')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='nationality')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filing_type', models.CharField(choices=[('VAT', 'VAT Return'), ('CT', 'Corporation Tax'), ('CRO', 'CRO Annual Return'), ('RBO', 'RBO Beneficial Ownership'), ('PAYE', 'PAYE/PRSI'), ('FINANCIAL_STATEMENTS', 'Financial Statements')], max_length=20, verbose_name='filing type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('FILED', 'Filed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='status')),
                ('filing_reference', models.CharField(blank=True, max_length=100, verbose_name='filing reference')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='filing date')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount due')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount paid')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='payment date')),
                ('generated_document', models.FileField(blank=True, null=True, upload_to='compliance/documents/%Y/%m/%d/', verbose_name='generated document')),
                ('filed_document', models.FileField(blank=True, null=True, upload_to='compliance/filed/%Y/%m/%d/', verbose_name='filed document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_filings', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_filings', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_filings', to=settings.AUTH_USER_MODEL)),
                ('tax_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.taxperiod')),
            ],
            options={
                'verbose_name': 'Filing',
                'verbose_name_plural': 'Filings',
                'ordering': ['-due_date'],
                'unique_together': {('company', 'tax_period', 'filing_type')},
            },
        ),
    ]
