# Generated by Django 4.2.29 on 2026-03-14 23:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(default='IE', max_length=2)),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('filed', 'Filed'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('tax_data', models.JSONField(blank=True, null=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-end_date'],
                'unique_together': {('company', 'country', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='TaxFiling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filing_type', models.CharField(max_length=50)),
                ('filing_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment_no', models.CharField(blank=True, max_length=100)),
                ('filing_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tax_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.taxperiod')),
            ],
        ),
    ]
