# Generated by Django 4.2.29 on 2026-03-15 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_beneficialowner_rboupload_shareholder_secretary_and_more'),
        ('compliance', '0002_companyofficer_personwithsignificantcontrol_and_more'),
    ]

    operations = [
    ]
