# Generated by Django 4.2.29 on 2026-03-15 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyprofile_country_companyprofile_state_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('compliance', '0004_ewaybill_hsncode_tdschallan_tdssection_tdsdeduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExciseDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_type', models.CharField(choices=[('import', 'Import'), ('manufacture', 'Manufacture'), ('release', 'Release from warehouse')], max_length=20)),
                ('declaration_period', models.DateField()),
                ('total_excise_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_due_date', models.DateField()),
                ('payment_made', models.BooleanField(default=False)),
                ('payment_date', models.DateField(null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('filed_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-declaration_period'],
            },
        ),
        migrations.CreateModel(
            name='ExciseGoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tobacco', 'Tobacco Products'), ('energy_drinks', 'Energy Drinks'), ('carbonated', 'Carbonated Drinks'), ('sweetened', 'Sweetened Drinks'), ('electronic_smoking', 'Electronic Smoking Devices'), ('liquids', 'Liquids for Electronic Smoking')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('customs_tariff_codes', models.TextField(help_text='Comma-separated HS codes')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('requires_marking', models.BooleanField(default=False, help_text='Digital tax stamps required')),
                ('marking_scheme', models.CharField(blank=True, help_text="e.g., 'DTS' for Digital Tax Stamps", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Excise goods categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_year', models.IntegerField()),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FreeZonePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_zone_name', models.CharField(choices=[('dubai_airport', 'Dubai Airport Freezone (DAFZ)'), ('jafza', 'Jebel Ali Free Zone (JAFZA)'), ('dmcc', 'Dubai Multi Commodities Centre (DMCC)'), ('dubai_south', 'Dubai South'), ('dwc', 'Dubai World Central'), ('rakftz', 'Ras Al Khaimah Free Trade Zone'), ('shams', 'Hamriyah Free Zone'), ('saif', 'Sharjah Airport International Free Zone'), ('ajman_ftz', 'Ajman Free Zone'), ('other', 'Other Free Zone')], max_length=50)),
                ('free_zone_license_no', models.CharField(max_length=100)),
                ('license_issue_date', models.DateField()),
                ('license_expiry_date', models.DateField()),
                ('has_qualifying_activities', models.BooleanField(default=True)),
                ('qualifying_activities_description', models.TextField()),
                ('non_qualifying_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExciseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_digital_stamp', models.BooleanField(default=False)),
                ('stamp_identifier', models.CharField(blank=True, max_length=100)),
                ('is_in_excise_warehouse', models.BooleanField(default=False)),
                ('warehouse_approval_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.excisegoodscategory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ExciseDeclarationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=20)),
                ('retail_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_retail_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('excise_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('excise_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compliance.excisegoodscategory')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='compliance.excisedeclaration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateTaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_period_start', models.DateField()),
                ('tax_period_end', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_of_goods_sold', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit_before_tax', models.DecimalField(decimal_places=2, max_digits=15)),
                ('non_deductible_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('exempt_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('reliefs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('losses_brought_forward', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('small_business_relief', models.BooleanField(default=False)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_free_zone_person', models.BooleanField(default=False)),
                ('qualifying_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('non_qualifying_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('filing_date', models.DateField(null=True)),
                ('filing_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('amended', 'Amended')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tax_period_end'],
                'unique_together': {('company', 'tax_period_start', 'tax_period_end')},
            },
        ),
    ]
