# Generated by Django 4.2.27 on 2026-04-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_rename_submitted_at_taxfiling_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficialowner',
            name='country_code',
            field=models.CharField(default='IE', max_length=2),
        ),
        migrations.AddField(
            model_name='director',
            name='country_code',
            field=models.CharField(default='IE', max_length=2),
        ),
        migrations.AddField(
            model_name='secretary',
            name='country_code',
            field=models.CharField(default='IE', max_length=2),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='country_code',
            field=models.CharField(default='IE', max_length=2),
        ),
    ]
