# Generated by Django 4.2.27 on 2026-04-06 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
        ('core', '0003_role_auditlog_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('JOURNAL_POST', 'Journal Posting'), ('DIVIDEND', 'Dividend Approval'), ('PURCHASE_ORDER', 'Purchase Order Approval'), ('TAX_FILING', 'Tax Filing Approval')], max_length=20)),
                ('reference_id', models.CharField(help_text='ID of the object being approved', max_length=100)),
                ('reference_model', models.CharField(help_text='Model name, e.g. JournalEntry, Dividend', max_length=50)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='PE', max_length=2)),
                ('request_notes', models.TextField(blank=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'approval workflow',
                'verbose_name_plural': 'approval workflows',
                'ordering': ['-created_at'],
            },
        ),
    ]
