# Generated by Django 4.2.27 on 2026-04-07 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_add_approval_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('SPREADSHEET', 'Spreadsheet'), ('DOCUMENT', 'Word/Text Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document attachment',
                'verbose_name_plural': 'document attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
