# Generated by Django 4.2.27 on 2026-03-14 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('finance', '0002_billwisedetail_costcentre_invoicetemplate_pricelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year_start', models.DateField(default='2025-04-01')),
                ('enable_cost_centres', models.BooleanField(default=True)),
                ('enable_budgets', models.BooleanField(default=True)),
                ('enable_billwise_details', models.BooleanField(default=True)),
                ('enable_multi_currency', models.BooleanField(default=False)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('stock_valuation_method', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('avco', 'Average Cost')], default='fifo', max_length=20)),
                ('enable_audit_trail', models.BooleanField(default=True)),
                ('alert_on_overdue', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.currency')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='company.companyprofile')),
            ],
        ),
    ]
