# Generated by Django 4.2.27 on 2026-03-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoicetemplate'),
        ),
    ]
