# Generated by Django 4.2.27 on 2026-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoice_cgst_amount_invoice_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='is_related_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
