# Generated by Django 4.2.29 on 2026-04-07 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
        ('finance', '0007_journalentryline_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='company.companyprofile'),
        ),
    ]
