from django.db import models
from django.utils.translation import gettext_lazy as _
from core.models import User
import uuid

class EInvoiceIRN(models.Model):
    """
    Invoice Reference Number (IRN) generated by government IRP portal
    Required for B2B invoices for companies exceeding turnover threshold.
    """
    company = models.ForeignKey('company.CompanyProfile', on_delete=models.CASCADE, related_name='einvoice_irns_in')
    STATUS_CHOICES = (
        ('generated', _('Generated')),
        ('cancelled', _('Cancelled')),
    )

    invoice = models.OneToOneField('finance.Invoice', on_delete=models.CASCADE, related_name='irn_detail')
    
    irn = models.CharField(max_length=64, unique=True, help_text="64 character hash")
    ack_no = models.CharField(max_length=20)
    ack_date = models.DateTimeField()
    signed_invoice = models.TextField(help_text="Signed JSON received from IRP")
    signed_qr_code = models.TextField(help_text="Signed QR Code string from IRP")
    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='generated')
    cancel_date = models.DateTimeField(null=True, blank=True)
    cancel_reason = models.CharField(max_length=200, null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("E-Invoice IRN")
        verbose_name_plural = _("E-Invoice IRNs")

    def __str__(self):
        return f"IRN for {self.invoice.invoice_number}"


class EInvoiceGenerator:
    """Helper to structure JSON payload for E-Invoicing API."""
    
    def __init__(self, company):
        self.company = company
        
    def generate_payload(self, invoice):
        """Generate JSON payload according to government schema."""
        
        # Calculate totals
        items = []
        sl_no = 1
        for item in invoice.items.all():
            items.append({
                "SlNo": str(sl_no),
                "PrdDesc": item.description or item.product.name,
                "IsServc": "Y" if item.product.type == 'service' else "N",
                "HsnCd": item.product.india_tax_class.hsn_code.code if hasattr(item.product, 'india_tax_class') and item.product.india_tax_class.hsn_code else "0000",
                "Barcde": "",
                "Qty": float(item.quantity),
                "FreeQty": 0,
                "Unit": "NOS", # Replace with actual unit mapping
                "UnitPrice": float(item.unit_price),
                "TotAmt": float(item.subtotal),
                "Discount": float(item.discount_amount),
                "PreTaxVal": 0,
                "AssAmt": float(item.subtotal),
                "GstRt": float(item.tax_rate),
                "IgstAmt": float(item.tax_amount) if invoice.customer.state_code != self.company.state_code else 0,
                "CgstAmt": float(item.tax_amount)/2 if invoice.customer.state_code == self.company.state_code else 0,
                "SgstAmt": float(item.tax_amount)/2 if invoice.customer.state_code == self.company.state_code else 0,
                "CesRt": 0,
                "CesAmt": 0,
                "CesNonAdvlAmt": 0,
                "StateCesRt": 0,
                "StateCesAmt": 0,
                "StateCesNonAdvlAmt": 0,
                "OthChrg": 0,
                "TotItemVal": float(item.total_amount)
            })
            sl_no += 1
            
        payload = {
            "Version": "1.1",
            "TranDtls": {
                "TaxSch": "GST",
                "SupTyp": "B2B",
                "RegRev": "N",
                "EcmGstin": None,
                "IgstOnIntra": "N"
            },
            "DocDtls": {
                "Typ": "INV",
                "No": invoice.invoice_number,
                "Dt": invoice.issue_date.strftime("%d/%m/%Y")
            },
            "SellerDtls": {
                "Gstin": self.company.tax_number,
                "LglNm": self.company.name,
                "TrdNm": self.company.name,
                "Addr1": self.company.address1,
                "Addr2": self.company.address2 or "",
                "Loc": self.company.city,
                "Pin": int(self.company.postal_code) if self.company.postal_code and self.company.postal_code.isdigit() else 110001,
                "Stcd": self.company.state_code,
                "Ph": self.company.phone,
                "Em": self.company.email
            },
            "BuyerDtls": {
                "Gstin": invoice.customer.tax_number,
                "LglNm": invoice.customer.name,
                "TrdNm": invoice.customer.name,
                "Pos": invoice.customer.state_code,
                "Addr1": invoice.customer.address1,
                "Addr2": invoice.customer.address2 or "",
                "Loc": invoice.customer.city,
                "Pin": int(invoice.customer.postal_code) if invoice.customer.postal_code and invoice.customer.postal_code.isdigit() else 110001,
                "Stcd": invoice.customer.state_code,
                "Ph": invoice.customer.phone,
                "Em": invoice.customer.email
            },
            "ItemList": items,
            "ValDtls": {
                "AssVal": float(invoice.subtotal),
                "CgstVal": float(invoice.tax_amount)/2 if invoice.customer.state_code == self.company.state_code else 0,
                "SgstVal": float(invoice.tax_amount)/2 if invoice.customer.state_code == self.company.state_code else 0,
                "IgstVal": float(invoice.tax_amount) if invoice.customer.state_code != self.company.state_code else 0,
                "CesVal": 0,
                "StCesVal": 0,
                "Discount": 0,
                "OthChrg": 0,
                "RndOffAmt": 0,
                "TotInvVal": float(invoice.total_amount),
                "TotInvValFc": float(invoice.total_amount)
            }
        }
        
        return payload
