# Generated by Django 4.2.27 on 2026-04-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CT1Computation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('net_profit_per_accounts', models.DecimalField(decimal_places=2, max_digits=15)),
                ('add_back_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('less_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taxable_profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.5, max_digits=5)),
                ('tax_payable', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('deadline_date', models.DateField()),
                ('responsible_party', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CO', 'Completed'), ('FI', 'Filed'), ('OV', 'Overdue')], default='PE', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='accounting_compliance.compliancedeadline')),
            ],
        ),
    ]
