# Generated by Django 4.2.27 on 2026-04-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
        ('accounting_compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPartyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(help_text='e.g. Director, Parent Company', max_length=200)),
                ('transaction_date', models.DateField()),
                ('transaction_nature', models.TextField(help_text='e.g. Loan, Management Fees, Rent')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_arm_length', models.BooleanField(default=True, help_text='Was the transaction at market value?')),
                ('disclosure_required', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_name', models.CharField(max_length=200)),
                ('declaration_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('dividend_per_share', models.DecimalField(decimal_places=4, max_digits=10)),
                ('number_of_shares', models.PositiveIntegerField()),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
    ]
