# Generated by Django 4.2.29 on 2026-03-13 11:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='dashboard name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('dashboard_type', models.CharField(choices=[('FINANCE', 'Finance Dashboard'), ('INVENTORY', 'Inventory Dashboard'), ('HR', 'HR Dashboard'), ('CRM', 'CRM Dashboard'), ('PROJECTS', 'Projects Dashboard'), ('CUSTOM', 'Custom Dashboard')], max_length=20, verbose_name='dashboard type')),
                ('layout_config', models.JSONField(default=dict, verbose_name='layout configuration')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups that can access this dashboard', to='auth.group', verbose_name='allowed groups')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='report name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('report_type', models.CharField(choices=[('TABLE', 'Table'), ('CHART', 'Chart'), ('PIVOT', 'Pivot Table'), ('SUMMARY', 'Summary'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='report type')),
                ('data_source', models.CharField(choices=[('FINANCE', 'Finance'), ('INVENTORY', 'Inventory'), ('HR', 'Human Resources'), ('CRM', 'CRM'), ('PROJECTS', 'Projects'), ('PURCHASING', 'Purchasing')], max_length=20, verbose_name='data source')),
                ('configuration', models.JSONField(default=dict, verbose_name='report configuration')),
                ('filters', models.JSONField(default=dict, verbose_name='report filters')),
                ('columns', models.JSONField(default=list, verbose_name='report columns')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('cache_duration', models.IntegerField(default=300, verbose_name='cache duration (seconds)')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups that can access this report', to='auth.group', verbose_name='allowed groups')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Definition',
                'verbose_name_plural': 'Report Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportPlugin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='plugin name')),
                ('plugin_type', models.CharField(choices=[('DATA_SOURCE', 'Data Source'), ('VISUALIZATION', 'Visualization'), ('EXPORT', 'Export Format'), ('TRANSFORMATION', 'Data Transformation')], max_length=20, verbose_name='plugin type')),
                ('module_path', models.CharField(max_length=500, verbose_name='module path')),
                ('config_schema', models.JSONField(default=dict, verbose_name='configuration schema')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='author')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Report Plugin',
                'verbose_name_plural': 'Report Plugins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='schedule name')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='frequency')),
                ('output_format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF'), ('HTML', 'HTML')], max_length=20, verbose_name='output format')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='cron expression')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('email_recipients', models.TextField(help_text='Comma-separated list of email addresses', verbose_name='email recipients')),
                ('email_subject', models.CharField(max_length=255, verbose_name='email subject')),
                ('email_message', models.TextField(blank=True, verbose_name='email message')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reportdefinition')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('CHART', 'Chart'), ('TABLE', 'Table'), ('METRIC', 'Metric'), ('PIVOT', 'Pivot Table'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='widget type')),
                ('title', models.CharField(max_length=255, verbose_name='widget title')),
                ('position_x', models.IntegerField(default=0, verbose_name='position X')),
                ('position_y', models.IntegerField(default=0, verbose_name='position Y')),
                ('width', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='width')),
                ('height', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='height')),
                ('config', models.JSONField(default=dict, verbose_name='widget configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reporting.dashboard')),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reportdefinition')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('execution_time', models.DurationField(blank=True, null=True, verbose_name='execution time')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='row count')),
                ('memory_usage', models.IntegerField(blank=True, null=True, verbose_name='memory usage (KB)')),
                ('result_data', models.JSONField(blank=True, null=True, verbose_name='result data')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='output file')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('parameters', models.JSONField(default=dict, verbose_name='execution parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.reportdefinition')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.schedule')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='reporting_r_status_4acfc6_idx'), models.Index(fields=['report_definition', 'created_at'], name='reporting_r_report__c16e49_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['report_type', 'data_source'], name='reporting_r_report__82ffff_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdefinition',
            index=models.Index(fields=['is_active', 'is_public'], name='reporting_r_is_acti_bea9fb_idx'),
        ),
    ]
