# Generated by Django 4.2.29 on 2026-04-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
        ('inventory', '0002_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company.companyprofile'),
        ),
    ]
