# Generated by Django 4.2.29 on 2026-03-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customergroup_customer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, help_text='State/Province code for tax purposes', max_length=5),
        ),
    ]
