# Generated by Django 4.2.29 on 2026-03-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(default='IE', help_text='ISO Country Code', max_length=2),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='state_code',
            field=models.CharField(blank=True, help_text='State/Province code for tax purposes', max_length=5),
        ),
    ]
