# Generated by Django 4.2.27 on 2026-03-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyprofile_country_companyprofile_state_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country_code',
            field=models.CharField(choices=[('IE', 'Ireland'), ('GB', 'United Kingdom'), ('IN', 'India'), ('AE', 'UAE')], default='IE', max_length=2),
        ),
    ]
