# Generated by Django 4.2.27 on 2026-03-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companyprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='financial_year_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
