# Generated by Django 4.2.27 on 2026-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_currency_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vat_goods_threshold',
            field=models.DecimalField(decimal_places=2, default=80000, max_digits=10),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vat_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vat_registration_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vat_services_threshold',
            field=models.DecimalField(decimal_places=2, default=42500, max_digits=10),
        ),
    ]
