# Generated by Django 4.2.29 on 2026-04-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_companyprofile_bank_name_companyprofile_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='enabled_modules',
            field=models.JSONField(default=dict, help_text='Enabled ERP modules for this company'),
        ),
    ]
