# Generated by Django 4.2.29 on 2026-03-15 04:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('tax_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficialOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('former_names', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('pps_number', models.CharField(blank=True, max_length=9)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(default='Ireland', max_length=50)),
                ('interest_type', models.CharField(choices=[('direct', 'Direct Ownership'), ('indirect', 'Indirect Ownership'), ('voting', 'Voting Rights'), ('control', 'Control via other means')], max_length=20)),
                ('interest_details', models.TextField(help_text='Describe the nature of interest')),
                ('shares_held', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage_held', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('voting_rights_percentage', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('became_owner_date', models.DateField()),
                ('ceased_owner_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(null=True)),
                ('identification_document', models.FileField(null=True, upload_to='rbo/id/')),
                ('proof_of_address', models.FileField(null=True, upload_to='rbo/address/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-percentage_held'],
                'unique_together': {('company', 'first_name', 'last_name', 'date_of_birth')},
            },
        ),
        migrations.CreateModel(
            name='RBOUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_corporate', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('corporate_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('country_incorporation', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('ordinary_shares_held', models.PositiveIntegerField(default=0)),
                ('preference_shares_held', models.PositiveIntegerField(default=0)),
                ('percentage_held', models.DecimalField(decimal_places=4, help_text='Percentage of total', max_digits=7)),
                ('date_joined', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_corporate', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('corporate_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(default='Ireland', max_length=50)),
                ('appointment_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RBORegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('filing_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to RBO'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('response_data', models.JSONField(null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owners_included', models.ManyToManyField(to='tax_engine.beneficialowner')),
            ],
            options={
                'ordering': ['-filing_date'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('total_authorised', models.PositiveIntegerField()),
                ('total_issued', models.PositiveIntegerField()),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_up_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dividend_rate', models.DecimalField(decimal_places=2, help_text='Dividend percentage', max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrdinaryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('total_authorised', models.PositiveIntegerField(help_text='Total shares authorised')),
                ('total_issued', models.PositiveIntegerField(help_text='Total shares issued')),
                ('nominal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_up_per_share', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('former_names', models.CharField(blank=True, help_text='Any former names', max_length=200)),
                ('pps_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{7}[A-Z]{1,2}$', 'Invalid PPS format')])),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('country', models.CharField(default='Ireland', max_length=50)),
                ('appointment_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('is_executive', models.BooleanField(default=True)),
                ('is_chairperson', models.BooleanField(default=False)),
                ('other_directorships', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
    ]
