# Generated by Django 4.2.29 on 2026-03-15 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('former_names', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('country_of_residence', models.CharField(max_length=50)),
                ('service_address_line1', models.CharField(max_length=100)),
                ('service_address_line2', models.CharField(blank=True, max_length=100)),
                ('service_address_city', models.CharField(max_length=50)),
                ('service_address_county', models.CharField(blank=True, max_length=50)),
                ('service_address_country', models.CharField(default='United Kingdom', max_length=50)),
                ('service_address_postcode', models.CharField(max_length=10)),
                ('residential_address_line1', models.CharField(max_length=100)),
                ('residential_address_line2', models.CharField(blank=True, max_length=100)),
                ('residential_address_city', models.CharField(max_length=50)),
                ('residential_address_county', models.CharField(blank=True, max_length=50)),
                ('residential_address_postcode', models.CharField(max_length=10)),
                ('residential_address_country', models.CharField(default='United Kingdom', max_length=50)),
                ('role', models.CharField(choices=[('director', 'Director'), ('secretary', 'Secretary'), ('llp_member', 'LLP Member')], max_length=20)),
                ('appointment_date', models.DateField()),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('is_psc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonWithSignificantControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_corporate', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('corporate_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('law_governed', models.CharField(blank=True, max_length=100)),
                ('legal_form', models.CharField(blank=True, max_length=100)),
                ('place_registered', models.CharField(blank=True, max_length=100)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('nature_of_control', models.CharField(choices=[('ownership', 'Ownership of shares >25%'), ('voting', 'Voting rights >25%'), ('board', 'Right to appoint/remove majority of board'), ('significant_influence', 'Significant influence or control'), ('trust', 'Trustee of trust with >25%'), ('firm', 'Member of firm with >25%')], max_length=50)),
                ('control_details', models.TextField(blank=True)),
                ('shares_held', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage_held', models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ('notified_date', models.DateField()),
                ('ceased_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmationStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('ordinary_shares_authorised', models.PositiveIntegerField()),
                ('ordinary_shares_issued', models.PositiveIntegerField()),
                ('ordinary_share_nominal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preference_shares_authorised', models.PositiveIntegerField(blank=True, null=True)),
                ('preference_shares_issued', models.PositiveIntegerField(blank=True, null=True)),
                ('psc_statement', models.TextField(help_text='Statement of capital, rights attached to shares')),
                ('is_trading', models.BooleanField(default=True)),
                ('sic_codes', models.CharField(help_text='SIC codes, comma separated', max_length=200)),
                ('filing_number', models.CharField(max_length=50, null=True, unique=True)),
                ('filed_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile')),
                ('current_officers', models.ManyToManyField(related_name='+', to='tax_engine.companyofficer')),
                ('filed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
