# Generated by Django 4.2.27 on 2026-03-20 23:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_companyprofile_financial_year_end'),
        ('tax_engine', '0005_excisedeclaration_excisegoodscategory_taxloss_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxfiling',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='taxfiling',
            old_name='submitted_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='taxfiling',
            old_name='acknowledgment_no',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='taxfiling',
            name='filing_data',
        ),
        migrations.RemoveField(
            model_name='taxfiling',
            name='filing_status',
        ),
        migrations.RemoveField(
            model_name='taxfiling',
            name='response_data',
        ),
        migrations.RemoveField(
            model_name='taxfiling',
            name='tax_period',
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.companyprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 3, 20)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='filed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='period',
            field=models.CharField(default='2024-Q1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('filed', 'Filed'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='taxfiling',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taxfiling',
            name='filing_type',
            field=models.CharField(choices=[('VAT3', 'VAT3 Return'), ('CT1', 'CT1 Corporation Tax'), ('CRO_B1', 'CRO B1 Annual Return'), ('RBO', 'RBO Beneficial Ownership'), ('PAYE', 'PAYE/PRSI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taxfiling',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FilingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('prepare', 'Prepare'), ('cfo', 'CFO Review'), ('board', 'Board Approval'), ('filed', 'Filed')], default='prepare', max_length=20)),
                ('filed_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_approvals', to=settings.AUTH_USER_MODEL)),
                ('cfo_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfo_approvals', to=settings.AUTH_USER_MODEL)),
                ('filing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tax_engine.taxfiling')),
            ],
        ),
    ]
