# Generated by Django 4.2.27 on 2026-04-04 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0007_journalentryline_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPartyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('subsidiary', 'Subsidiary'), ('associate', 'Associate'), ('joint_venture', 'Joint Venture'), ('director_related', 'Director Related'), ('key_management', 'Key Management Personnel'), ('other', 'Other Related Party')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='related_party_detail', to='finance.journalentryline')),
            ],
        ),
    ]
